<?php

namespace AppBundle\Repository;

/**
 * PetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHumanRut($rut)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Pet p JOIN p.human h WHERE h.rut = :rut'
            )
            ->setParameter('rut', $rut)
            ->getResult();
    }
}
